### PR TITLE
[Docs] Update yb-platform setup for Azure - removed NTP, added troubleshooting messages. See below

### PR DESCRIPTION
**Pull request by sumitdatabase**
Changes --

1) replaced the image ( platform-azure-prepare-cloud-env-4.png  
 )  that shows NTP setup for setting up azure provider and removed the instructions for NTP, we do not do NTP anymore. 

2) at the bottom, added a standard troubleshooting message when installation fails.

3) added a couple of screenshots associated with the failed installations.  ( platform-azure-prepare-cloud-env-5.png and platform-azure-prepare-cloud-env-6.png  )

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@sumitdatabase Could you, please, provide a link to the dev ticket that removes NTP from the UI? 
NTP documentation has been recently added as per request from Platform dev. There's also an outstanding ticket for more NTP doc/chages: https://yugabyte.atlassian.net/browse/PLAT-3947

CC: @rahulb-yb

**Comment by sumitdatabase** [comment]
> @sumitdatabase Could you, please, provide a link to the dev ticket that removes NTP from the UI? NTP documentation has been recently added as per request from Platform dev. There's also an outstanding ticket for more NTP doc/chages: https://yugabyte.atlassian.net/browse/PLAT-3947
> 
> CC: @rahulb-yb

@lizayugabyte , I do not have a ticket number.  Also was not aware of the ticket you mention for NTP changes for 2.14. But our current preview doc is for 2.13 and this page is already updated for 2.14 ? 

My test was done using 2.12.5.0-b24 version - with the screenshots I have added. I am happy to test with 2.13.x - if you want me to.

Let me know whether we should go in with this, and add the NTP section later again or - I can back out this NTP removal parts and leave the troubleshooting messages. 

Thanks !

**Comment by lizayugabyte** [comment]
@sumitdatabase We have a Level 1 section for troubleshooting: https://docs.yugabyte.com/preview/yugabyte-platform/troubleshoot/
Changes to the NTP part should be reversed, thank you.

As a general rule, any doc PR should be linked to either Jira or git ticket that requests this documentation, describing the purpose and the release the changes should be applied to.

**Comment by sumitdatabase** [comment]
> @sumitdatabase We have a Level 1 section for troubleshooting: https://docs.yugabyte.com/preview/yugabyte-platform/troubleshoot/ Changes to the NTP part should be reversed, thank you.
> 
> As a general rule, any doc PR should be linked to either Jira or git ticket that requests this documentation, describing the purpose and the release the changes should be applied to.

@lizayugabyte - Understood, LMK if I should simply close this PR? 

On the L1 troubleshooting [page](https://docs.yugabyte.com/preview/yugabyte-platform/troubleshoot/install-upgrade-yp-issues/), I do not see anything similar to what I suggested and ran into during install, for Azure troubleshooting. I can open an issue on that and leave it that way if that is appropriate.

In addition, it seems that we should have a link to the same L1 troubleshooting page from the setup Azure [page](https://docs.yugabyte.com/preview/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/azure/) so if setup fails people can jump to that. 

And again I am happy to do what you suggest is appropriate. Thanks

Also 

Also I do not see a link

**Comment by sumitdatabase** [comment]
Based on comments from @lizayugabyte , closing this PR not to move forward..

**Pull request closed without merging**
