### PR TITLE
[docs] Update tablespaces.md

### PR DESCRIPTION
**Pull request by kerneljake**
multi-region transcends one country in this case

### CODE REVIEW

**Comment by kerneljake** [comment]
The labels in two of the preceding diagrams would need to change, too.

**Comment by polarweasel** [comment]
Hey @deeps1991 this page is yours. Can you help @kerneljake out?

**Comment by deeps1991** [comment]
Hi @kerneljake Nice find, thanks for pointing this out! The changes look good. I have also edited the images like you requested;  they are here - https://docs.google.com/document/d/1Sb-townaCIJBwW-bOE__B6_A38g45zffEIE1gtrnS7Y/edit?usp=sharing
If you can, please could you put in the corrected images that are present in the above doc?

**Comment by kerneljake** [comment]
@polarweasel Incorporating the images in the google doc is more in your court than mine.  I do not know how the doc team prefers to do that.

**Comment by deeps1991** [comment]
@kerneljake @polarweasel Nvm, I realized couple days ago that I have a couple more changes to the row level geo partitioning sections, I am making the change to the images as part of that.

Thanks @kerneljake once again for noting this!

**Review by deeps1991 — APPROVED** [review]

**Pull request merged**
