### PR TITLE
New pr for issue-7543

### PR DESCRIPTION
**Pull request by triump2020**
[#7992 ]

### CODE REVIEW

**Comment by bmatican** [comment]
why the new PR, rather than just amend the old one? https://github.com/yugabyte/yugabyte-db/pull/7992

**Comment by triump2020** [comment]
> why the new PR, rather than just amend the old one? #7992

  Sorry,   I  re-forked the repo, want to solve the unexpected commit log of 'thirdpaty' . seems it 's not a good idea.

**Comment by triump2020** [comment]
I run the cmd :  /bin/undo_submodule_changes.sh ,  still have a change log of thirdpaty.

**Comment by bmatican** [comment]
@triump2020 have you rebased on our latest master and then ran the undo_submodule_changes script?

**Comment by tedyu** [comment]
I run the following command in order to discard unwanted change to thirdparty:

git submodule update --init --recursive

**Comment by triump2020** [comment]
@bmatican @tedyu  Thanks for your pointers !  Now , the change log to thirdparty seems to be removed .

**Comment by bmatican** [comment]
@triump2020 do you want to drop this PR then and go back to the original one? since that has the comment history, etc, so would be nicer to merge that in, once done

**Comment by triump2020** [comment]
@bmatican   How did i go back to the original PR [#7992] ?  since the original  `triump2020:issue-7543` branch had been deleted.  
image

**Comment by triump2020** [comment]
Sorry ,  i 'm not familiar with git .

**Review by bmatican — APPROVED** [review]
ok, no worries, we'll keep this PR instead and you can abandon the other one! I'm accepting this for now, but I'll run it quickly through our internal CI to make sure there's no unexpected issues and I'll merge it afterwards!

Thanks for the quick work @triump2020

**Pull request merged**
