### PR TITLE
[docs] [#11113] Remove duplicate entries in left navigation

### PR DESCRIPTION
**Pull request by rajmaddy89**
Changes
--
1. There are a number of places in the docs where the left navigation sections repeat. 

The other areas include:

Yugabyte Cloud
Integrations
Reference
Releases
FAQ
It would be good to remove these and hoist the items inside these sections to the level above.

2. Rename `Back up and restore universes` to `Back up universes` under YB Platform section based on suggestion by @rkarthik007 
3. Change weights to preserve existing order.

TODO
--
I will attach more screenshots tomorrow for this PR changes

### CODE REVIEW

**Comment by rajmaddy89** [comment]
Reference Issue : https://github.com/yugabyte/yugabyte-db/issues/11113

**Comment by rajmaddy89** [comment]
Removing Integrations topic within Integration section
Integrations

Removing Releases topic within releases section
Releases

Removing Yugabyte Platform topic within Yugabyte Platform section due to repetition
YB Platform

Removing Yugabyte Core topic within Yugabyte Core section due to repetition
YB-CORE

Renaming "Back up and restore universes" section to "Back up universes" but the linktitle does not change on the right side
renaming backup-universes

**Comment by rajmaddy89** [comment]
Removing Releases topic within releases section
Releases

**Comment by rajmaddy89** [comment]
Removing Yugabyte Platform topic within Yugabyte Platform section due to repetition
YB Platform

**Comment by rajmaddy89** [comment]
Removing Yugabyte Core topic within Yugabyte Core section due to repetition
YB-CORE

**Comment by rajmaddy89** [comment]
Renaming "Back up and restore universes" section to "Back up universes" but the linktitle does not change on the right side
renaming backup-universes

**Review by polarweasel — APPROVED** [review]
LGTM! I'm amazed that the whole issue was an own-goal, in that not every page actually _needs_ a parent. I'm glad you were able to sort this out!

**Review by ddhodge — APPROVED** [review]
LGTM

**Pull request merged**
