### PR TITLE
 [docs] PR for Clarify that ssl_protocols gflag for yb-tserver/master is not a "min" setting (Doc10018)

### PR DESCRIPTION
**Pull request by lizayugabyte**
Preview: https://deploy-preview-10691--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/security/enable-encryption-in-transit/#enforcing-tls-versions

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@iSignal Could you, please, review the change?

**Comment by lizayugabyte** [comment]
@iSignal Could you, please, review the change?

**Review by ddhodge — APPROVED** [review]
LGTM

**Comment by lizayugabyte** [comment]
This PR has been open for review for more than 2 weeks. The issue reporter has been contacted multiple times but haven't reviewed the document. I'm going to close the ticket based on the approval from the second reviewer. Should changes be required, I'll address them via a new PR.

**Pull request merged**
