### PR TITLE
[Docs] PR for VMware Tanzu cloud provider documentation Doc7622

### PR DESCRIPTION
**Pull request by lizayugabyte**

### CODE REVIEW

**Comment by nchandrappa** [comment]
@lizayugabyte Current documentation under the [VMware Tanzu page](https://docs.yugabyte.com/latest/yugabyte-platform/configure-yugabyte-platform/set-up-cloud-provider/vmware-tanzu/) is outdated, we need to replace it with the new content I've provided here. 

Also, The outdated (legacy) content should more under the appendix. Under the title `VMware Tanzu Application Service`.

**Review by nchandrappa — CHANGES_REQUESTED** [review]
Current Commit doesn't replace the outdated content. Please see my comments on the Github issue.

**Comment by lizayugabyte** [comment]
@nchandrappa Sorry, I misunderstood the doc requirement (didn't realize the currently published document needed to be replaced with the new one, as opposed to the new one added as a new section to the old doc).
I implemented the review comment. Please let me know if that's what was required.
Please note that our documentation site is currently structured in a way that doesn't allow separate Appendix pages (these need to be appended to the end of a book structure). I created a legacy Appendix at the end of the page.

**Review by nchandrappa — APPROVED** [review]
@lizayugabyte Thank you for making the changes. LGTM.

**Pull request merged**
