### PR TITLE
[Docs] PR for Add Peer certificates configuration for HA in platform docs

### PR DESCRIPTION
**Pull request by lizayugabyte**
Addresses https://yugabyte.atlassian.net/browse/PLAT-5632

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@sb-yb Please take a look at this doc PR. I don't think we need to include specific info on how to export peer certificates on different browsers because it's not part of the platform configuration; it's up to the user to find this information online.

**Comment by sb-yb** [comment]
Also would be nice if you put circle to highlight Add Peer Cert button in the image.

**Comment by lizayugabyte** [comment]
@sb-yb I'm not sure what you mean by "repeats 3 times". It's described once in [Configure the active instance](https://deploy-preview-14530--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/manage-deployments/high-availability/#configure-the-active-instance) and once in [Configure standby instances](https://deploy-preview-14530--infallible-bardeen-164bc9.netlify.app/preview/yugabyte-platform/manage-deployments/high-availability/#configure-standby-instances). 
The reason I didn't extract this into one section is because the screenshots are different (one show Active and the other one shows Standby).

**Comment by lizayugabyte** [comment]
@sb-yb I deleted the paragraph that was added by mistake. Can I merge the PR now?

**Comment by lizayugabyte** [comment]
@sb-yb I fixed the error. Can I merge the PR now?

**Comment by lizayugabyte** [comment]
@sb-yb Can we merge the PR ?

**Comment by lizayugabyte** [comment]
I'm going to merge this PR. If changes are required, they'll be addressed via an improvement ticket and a new PR.

**Pull request merged**
