### PR TITLE
[docs] update docs build

### PR DESCRIPTION
**Pull request by polarweasel**
Updating node version, as well as some package versions.

Please test this branch locally! (And make sure you're running node 14 or 16.)

1. `cd docs`
1. `rm -rf node_modules`
1. `npm run build`
1. `npm start`

If either of the `npm` steps fails, please let me know!

### CODE REVIEW

**Review by ddhodge — APPROVED** [review]
LGTM

**Review by yb-andrew — COMMENTED** [review]
Looks good. One thing that is helpful is pinning the versioning, which we started to enforce on the product side as well. What is means is removing all the carets symbols in the package.json file
Example: 
`"babel": "^6.23.0"` -> `"babel": "6.23.0"`

**Comment by polarweasel** [comment]
Thanks Andrew! While we're looking at the build, should Netlify be running `npm ci` or `npm install` for the deployments?

**Comment by yb-andrew** [comment]
Netlify should run `npm ci` so that it uses `package-lock.json` file for dependency tree. This way you get the closest environment (w.r.t. node_modules) to your local machine.

**Comment by polarweasel** [comment]
Updated the build command in the Netlify UI. Thanks!

**Review by yb-andrew — APPROVED** [review]

**Review by ddhodge — APPROVED** [review]
LGTM

**Pull request merged**
