### PR TITLE
[Docs] Best practices around partition keys #13004

### PR DESCRIPTION
**Pull request by ddhodge**
#13004

@netlify /preview/api/ysql/the-sql-language/statements/ddl_create_table/#primary-key

### CODE REVIEW

**Review by ddorian — APPROVED** [review]
Can you add a small section to YSQL Best Practices that links to this?

**Comment by ddhodge** [comment]
> Can you add a small section to YSQL Best Practices that links to this?

Should it go there instead?

**Comment by ddorian** [comment]
> Should it go there instead?

Ok.

**Comment by ddhodge** [comment]
PARTITION BY clause not on CREATE TABLE page at all - is that an oversight?

**Review by aishwarya24 — APPROVED** [review]
LGTM. Backport to stable ?

**Comment by ddorian** [comment]
> PARTITION BY clause not on CREATE TABLE page at all - is that an oversight?

There's an issue for it https://github.com/yugabyte/yugabyte-db/issues/9201

**Pull request merged**
