### PR TITLE
[#5734] Disable "Delete provider" for on-premises provider

### PR DESCRIPTION
**Pull request by gaurav061**

### CODE REVIEW

**Comment by gaurav061** [comment]
Change: Disable Delete-provider button if provider is linked with any universe for on-prem.

**Review by nishantSharma459 — COMMENTED** [review]
LGTM. Someone else can also take a look.

**Review by jaydeepkumara — APPROVED** [review]

**Comment by sshev** [comment]
@gaurav061 is the linked issue https://github.com/yugabyte/yugabyte-db/issues/5732 correct for this PR?

**Comment by gaurav061** [comment]
> @gaurav061 is the linked issue #5732 correct for this PR?

Sorry...my Bad it's #5734 .

**Review by sshev — APPROVED** [review]
LGTM

**Review by jaydeepkumara — APPROVED** [review]

**Pull request merged**
