### PR TITLE
[docs] Update yb-pg-stat-get-queries to yb_terminated_queries

### PR DESCRIPTION
**Pull request by divyansh-yb**
Updated the doc to use yb_terminated_queries instead of yb_pg_stat_get_queries. In the section 'Return a query from another database', database name is being used instead of OID to query from the view, since yb_terminated_queries doesn't have an OID field.

This change applies to 2.17.3 and 2.18. So preview is sufficient.

Build preview : https://deploy-preview-17065--infallible-bardeen-164bc9.netlify.app/preview/explore/query-1-performance/yb-pg-stat-get-queries/

### CODE REVIEW

**Comment by timothy-e** [comment]
I'm getting a page not found error:
Screenshot 2023-04-27 at 1 51 05 PM

**Comment by aishwarya24** [comment]
> I'm getting a page not found error: Screenshot 2023-04-27 at 1 51 05 PM

@timothy-e Can you please check now.

**Comment by timothy-e** [comment]
Content looks good to me!

This might be out of the scope of this change, but I noticed when I search for `yb_pg_stat...` I see the old page, and when I click on it, it shows me the new content with the new title. When I search for `yb_terminated..` I don't get any results. 

Screenshot 2023-04-27 at 3 46 51 PM

**Comment by aishwarya24** [comment]
> Content looks good to me!
> 
> This might be out of the scope of this change, but I noticed when I search for `yb_pg_stat...` I see the old page, and when I click on it, it shows me the new content with the new title. When I search for `yb_terminated..` I don't get any results.
> 
> Screenshot 2023-04-27 at 3 46 51 PM

I think this is expected behaviour and the search crawler takes a while to refresh the details. Thanks for checking though :)

**Review by ddhodge — APPROVED** [review]
LGTM

**Pull request merged**
