### PR TITLE
 [docs] PR for Prepare the Google Cloud Platform (GCP) environment (Doc-11438) 

### PR DESCRIPTION
**Pull request by lizayugabyte**
Addresses:
https://github.com/yugabyte/yugabyte-db/issues/11438
and
https://yugabyte.atlassian.net/browse/PLAT-2826

Preview: https://deploy-preview-11563--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/

### CODE REVIEW

**Comment by VijiYB** [comment]
@lizayugabyte - Added Lareb as reviewer too. He is currently running some of the commands to verify mainly the Service Account part.

**Comment by zlareb1-yb** [comment]
**Here are my Comments**:
1. Creating a Project is mentioned [Optional](https://deploy-preview-11563--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#create-a-project-optional) but looks like Project is mandatory to create a Service account
2. I haven't been able to execute the doc with Owner, Admin level perms. Do we need to mention [Owner](https://deploy-preview-11563--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#:~:text=section%2C%20select%20the-,Owner,-role.) level perms on Project?
3. [Here](https://deploy-preview-11563--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#:~:text=Replace-,NN.NN.NN.NN,-with%20the%20IP) we should name which IP we should connect to - External/Internal

**For better UX**:
We can mention copy email address [here](https://deploy-preview-11563--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#:~:text=Complete%20the%20Service%20account%20details%20fields%20and%20click%20Create%20and%20Continue.) instead of [here](https://deploy-preview-11563--infallible-bardeen-164bc9.netlify.app/latest/yugabyte-platform/install-yugabyte-platform/prepare-environment/gcp/#:~:text=To%20retrieve%20the%20email%20information%2C%20navigate%20to%20IAM%20%26%20Admin%20%3E%20Service%20Accounts%20and%20copy%20the%20Email%20value.)

**Note** - With my perms (only user level perms) I was able to ssh to the instance using External IP

**Comment by zlareb1-yb** [comment]
@lizayugabyte as I was able to try only with User role and Connect it with External IP, I am not very sure what to update here. Maybe we should also check with someone who has admin and/or Owner level perms as well to write detailed doc @VijiYB

**Comment by lizayugabyte** [comment]
@VijiYB Would you be able to verify a couple things that @zlareb1-yb couldn't ? (see his comments for details)

**Comment by lizayugabyte** [comment]
The couple points that should be verified are not new content. We had those in the doc for a while, so I believe these steps were verified when written. I'll close this tickets, as most of what needed to be updated has been addressed. I'll keep in mind the raised uncertainties for future doc improvements.

**Comment by VijiYB** [comment]
Sounds good @lizayugabyte . Sorry was unable to verify.

**Pull request merged**
