### PR TITLE
[docs] Added Docker file

### PR DESCRIPTION
**Pull request by CharlotteRose**
This commit contains changes to README to include instructions for docker file (in /docs) along with corrections to instructions.

### CODE REVIEW

**Comment by rkarthik007** [comment]
This looks good to me overall @CharlotteRose! Thanks for adding this.

@bllewell - could you please review? Given you have some changes outstanding for the README file - please take a look and approve if this looks ok? You may need to merge these changes into yours.

**Comment by tylarb** [comment]
@dotyjim-work you should take a look as well

**Comment by tylarb** [comment]
tested - works for me.

**Comment by CharlotteRose** [comment]
@bllewell  - closing per our discussion. I will rebase and reapply the changes once your additions have been merged.

**Pull request closed without merging**
