### PR TITLE
[docs] [infra] hugo shortcode updates

### PR DESCRIPTION
**Pull request by polarweasel**
**Problem**: external-pointing links in admonitions (note, tip, warning) weren't getting styled correctly. This fixes that, and applies the same fix to several other shortcodes that turned out to have the same problem.

The updates allow external URLs (meaning any link that starts with `http` or `https`) to get styled as such, with the usual icon and a target of `_blank`. To test, have a look at the Cloud Troubleshooting page, at the bottom, and verify that the link to Yugabyte Support shows as external now. Or, have a look at the first note on the [ddl_alter_table reference page](https://deploy-preview-11399--infallible-bardeen-164bc9.netlify.app/latest/api/ysql/the-sql-language/statements/ddl_alter_table/#syntax), and verify that the link is styled correctly.

As for the **grammar and syntax diagrams**, the `includeMarkdown` shortcode has changed. So if they're still rendering correctly, that change passes the test. This PR also includes output from the latest version of the RRDiagram tool, which adds the `ebnf` language to the grammar code blocks, so those are syntax-highlighted now.

As a random example, please also verify that the code blocks and diagrams work on this page or another like it:

@netlify /latest/api/ysql/exprs/aggregate_functions/invocation-syntax-semantics/

### CODE REVIEW

**Comment by bllewell** [comment]
This page has no notes, tips, or warnings. So what is there to check. The syntax diagrams seem to have come out OK. But why suspect that they would not?

**Comment by polarweasel** [comment]
@bllewell I've updated the link in the note that started this whole thing when you pointed out that links in notes weren't getting styled correctly. description to point to a better example: the bottom of the Cloud Troubleshooting page has a link to support that is generated with a shortcode. Those links have the same problem, for the same reason (the `markdownify` function), as the admonitions.

Have a look at the first note on the [ddl_alter_table reference page](https://deploy-preview-11399--infallible-bardeen-164bc9.netlify.app/latest/api/ysql/the-sql-language/statements/ddl_alter_table/#syntax), and notice that the link (which is in markdown format as of commit [02d7ee4](https://github.com/yugabyte/yugabyte-db/pull/11399/commits/02d7ee464bd801ccaa2ab2e0d1ed33f49ccb6791), is styled correctly.

As for the syntax diagrams, the `includeMarkdown` shortcode has changed. So if they're still rendering correctly, that change passes the test. 👍

**Review by ddhodge — APPROVED** [review]
LGTM

**Review by lizayugabyte — APPROVED** [review]
LGTM

**Pull request merged**
