### PR TITLE
[Docs] Revisit "Point-in-time recovery" page

### PR DESCRIPTION
**Pull request by vkulichenko**
@netlify /preview/manage/backup-restore/point-in-time-recovery/

### CODE REVIEW

**Comment by vkulichenko** [comment]
Update page: https://deploy-preview-12404--infallible-bardeen-164bc9.netlify.app/preview/manage/backup-restore/point-in-time-recovery/

**Review by polarweasel — COMMENTED** [review]
Looks like #8259, colocated tables, is closed now (markdown, line 205)

**Review by polarweasel — APPROVED** [review]
@vkulichenko Other than the one issue that appears to be closed now (please check to see if it should be removed from the known issues), this should be good to go.

Final question: do these changes apply only to preview (2.13), or also to stable (2.12)?

**Comment by vkulichenko** [comment]
> @vkulichenko Other than the one issue that appears to be closed now (please check to see if it should be removed from the known issues), this should be good to go.
The "Limitations" sections has multiple issues. It needs to be revisited, which I have a separate ticket for: #12231

**Pull request merged**
