### PR TITLE
[docs] Manual fix for a yb-version not rendering correctly.

### PR DESCRIPTION
**Pull request by aishwarya24**

### CODE REVIEW

**Review by ddhodge — APPROVED** [review]
why doesn't this work

**Comment by aishwarya24** [comment]
> why doesn't this work

not sure, this looked like the only instance of being linked from includeMarkdown shortcode. Somehow this combination doesn’t work. Requires some debugging.

**Comment by samiahmedsiddiqui** [comment]
@ddhodge I think we should make it configurable otherwise we need to manually update this version every time when the new preview version release.

**Comment by ddhodge** [comment]
> @ddhodge I think we should make it configurable otherwise we need to manually update this version every time when the new preview version release.

Yes - but how. It wasn't working, but don't know how to fix.

**Pull request merged**
