### PR TITLE
[#7724] docs: switch to GUC var yb_index_state_flags_update_delay

### PR DESCRIPTION
**Pull request by jaki**
Replace mentions of flag `ysql_index_state_flags_update_delay_ms`
(actually supposed to be `TEST_ysql_index_state_flags_update_delay_ms`)
with GUC variable `yb_index_state_flags_update_delay`.

### CODE REVIEW

**Comment by jaki** [comment]
Don't merge this PR until D10983 lands.

**Comment by polarweasel** [comment]
Thanks @jaki!

If this shouldn't be merged pending another change, please set it to draft mode. We can get it reviewed and approved, but draft prevents it from being merged by accident.

**Review by polarweasel — CHANGES_REQUESTED** [review]
Two super-nitpicky changes only :)

**Review by polarweasel — APPROVED** [review]
GTG

**Pull request merged**
