### PR TITLE
[Docs] Badcode highlight

### PR DESCRIPTION
**Pull request by samiahmedsiddiqui**
Highlight badcode or make wrong coding practices stand out  than regular code.

### CODE REVIEW

**Review by premkumr — APPROVED** [review]
Looks good. Thanks, @samiahmedsiddiqui.

It would have been good to have a demo.

**Comment by samiahmedsiddiqui** [comment]
@premkumr Badcode added with the preview.
https://deploy-preview-16704--infallible-bardeen-164bc9.netlify.app/preview/contribute/docs/docs-style/#code-blocks

**Review by premkumr — APPROVED** [review]
Looks good @samiahmedsiddiqui! I made a minor change in the example. You can merge it.

**Comment by samiahmedsiddiqui** [comment]
@premkumr I don't have merge right. Can you please do it?

**Pull request merged**
