### PR TITLE
[docs] [explore] fix broken links for some sections in CDCSDK-server

### LINKED ISSUE #13335: [Docs] Broken link in cdcsdk-server
### Description

https://docs.yugabyte.com/preview/explore/change-data-capture/cdcsdk-server/#record-structure
has https://docs.yugabyte.com/preview/explore/change-data-capture/change-data-capture/debezium-connector-yugabytedb.md#data-change-events which is broken.

### PR DESCRIPTION
**Pull request by aishwarya24**
resolves #13335
@netlify /preview/explore/change-data-capture/cdcsdk-server/

### CODE REVIEW

**Comment by hari90** [comment]
#### Mapping records to S3 objects
Also has  a similar broken link

**Comment by hari90** [comment]
There are 3 links with "change-data-capture/debezium-connector-yugabytedb". do they all need to be changed?

**Comment by aishwarya24** [comment]
@hari90 , Thank you. Yes, ill take a look and change them.

**Review by hari90 — CHANGES_REQUESTED** [review]
I think there is one more in line 283

**Comment by hari90** [comment]
> I think there is one more in line 283

Opps my bad. Looks like you fixed them all!

**Review by hari90 — APPROVED** [review]

**Pull request merged**
