### PR TITLE
[docs] Fixed command to list tables

### PR DESCRIPTION
**Pull request by pgyogesh**
Fixed the issue #11416

### CODE REVIEW

**Review by polarweasel — APPROVED** [review]

**Comment by polarweasel** [comment]
@pgyogesh We can't merge this PR without a signed contributor license agreement. Also please see @aishwarya24's outstanding question.

**Comment by lizayugabyte** [comment]
@polarweasel @aishwarya24 This PR and its linked ticket have been stuck in limbo for a long time. We've had a few people pointing out different pages that have commands missing master_address. Our support guys (e.g. Jason) all say that master_address followed by a list of IP addresses is necessary to run commands.
Perhaps it would be a good idea to finish this PR.

**Comment by aishwarya24** [comment]
> @polarweasel @aishwarya24 This PR and its linked ticket have been stuck in limbo for a long time. We've had a few people pointing out different pages that have commands missing master_address. Our support guys (e.g. Jason) all say that master_address followed by a list of IP addresses is necessary to run commands. Perhaps it would be a good idea to finish this PR.

Sure @lizayugabyte . Sounds good. @pgyogesh , Could you please sign the CLA and merge it.(after resolving the merge conflict) cc @polarweasel

**Comment by lizayugabyte** [comment]
@aishwarya24 @polarweasel Perhaps merge conflicts are too extensive

**Pull request merged**
