### PR TITLE
[DOC] PR for OIDC Configuration instructions in the doc needs improvement

### PR DESCRIPTION
**Pull request by lizayugabyte**
Addresses https://yugabyte.atlassian.net/browse/PLAT-5744

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@ckamaleo Could you, please, review this doc PR ?

**Comment by ckamaleo** [comment]
@lizayugabyte It would be helpful to have the appropriate values in the fields. (currently the fields are empty)

**Comment by lizayugabyte** [comment]
@ckamaleo Unfortunately, I don't have permissions to access some of the Admin portions of YBA, including this one, so I'm not able to provide a new screenshot. It's is rather a standard procedure for our docs to include screenshots with blank fields and provide detailed descriptions on how to complete these fields. This is related to doc maintenance issues that arise when dev changes are made to the product. 
I'll keep your request in mind, but right now I'd rather merge the PR to avoid conflicts that often happen when PRs are kept open for too long.

**Comment by lizayugabyte** [comment]
@ckamaleo Could you, please, take a look at my response to your comment and let me know if I can merge the PR now?

**Comment by ckamaleo** [comment]
Hi @lizayugabyte Sure, Please go ahead and complete the merge.

**Pull request merged**
