### PR TITLE
[docs] Add architecture doc for savepoints

### PR DESCRIPTION
**Pull request by robertsami**

### CODE REVIEW

**Comment by ymahajan** [comment]
Good initial draft @robertsami. 'Notes' section - is it a placeholder for now?, seems like a limitation or future work you are highlighting. We can elaborate more on future items - consider the major open tickets or a product gaps that users should be worry about.

**Comment by ymahajan** [comment]
@robertsami  We can also add Usage section describing how this feature will be used, key syntax etc. You can refer to the other design documents in this folder.

**Comment by robertsami** [comment]
@ymahajan thanks for the input -- since the changes were modified/accepted by @polarweasel i went ahead and merged but will send you both a separate PR with the further changes

**Comment by robertsami** [comment]
@ymahajan @polarweasel see here: https://github.com/yugabyte/yugabyte-db/pull/10526

**Pull request merged**
