### PR TITLE
docs: add vulnerability disclosure policy

### PR DESCRIPTION
**Pull request by polarweasel**
~~Edited with Cyrus and Liza. Note that this PR isn't ready to merge yet, but please review the content, formatting, and suggested location (/latest/legal).~~

~~Next steps: adding links to this page from the appropriate places.~~

**Update**: ready for review. FAQ links added in general and platform, and final (for now) home is under `/latest/secure`.

### CODE REVIEW

**Comment by polarweasel** [comment]
Cyrus commented: move out of legal.

My suggestion: under FAQ instead. @ameyb what do you think?

**Comment by lizayugabyte** [comment]
@polarweasel @CyrusWadia @ameyb I'd suggest creating a new folder under Misc for this. If we expect more of this type of documents, then we could name the new folder Disclosure or something like that.

**Comment by lizayugabyte** [comment]
_The net impact is that application developers have to select an API first before undertaking detailed database schema/query design and implementation._ -- should "application developers" be changed to "you" to be consistent with _Please follow the steps in the vulnerability disclosure policy to report a vulnerability to our security team. The policy outlines our commitments to you when you disclose a potential vulnerability, the reporting process, and how we will respond._ ?

**Comment by lizayugabyte** [comment]
Looks good

**Review by lizayugabyte — APPROVED** [review]

**Review by ameyb — APPROVED** [review]
Looks good, thanks for making the changes and getting this up in such a short time @polarweasel & @lizayugabyte

**Pull request merged**
