### PR TITLE
[docs] PR for Missing option on command causes failure

### PR DESCRIPTION
**Pull request by lizayugabyte**
Addresses https://yugabyte.atlassian.net/browse/PLAT-3871

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@jasonriddell Could you, please, review this doc PR ?

**Comment by lizayugabyte** [comment]
@jasonriddell Could you, please, review this doc PR ?

**Comment by lizayugabyte** [comment]
@jasonriddell Could you, please, let me know when you are planning to review this doc PR ?

CC: @nbhatia-yb

**Comment by lizayugabyte** [comment]
@jasonriddell Could you, please, let me know when you are planning to review this doc PR ?

**Comment by jasonriddell** [comment]
Change looks good, @lizayugabyte apologies for my delay. Thank you!

**Review by jasonriddell — APPROVED** [review]
Change looks good, @lizayugabyte apologies for my delay. Thank you!

**Comment by lizayugabyte** [comment]
Too many conflicts to resolve.

**Pull request closed without merging**
