### PR TITLE
docs release for v2.6

### PR DESCRIPTION
**Pull request by polarweasel**
Should be ready to go once the 2.6 release is live...

@netlify /stable/

### CODE REVIEW

**Comment by ddhodge** [comment]
404s from Platform > Overview page: https://deploy-preview-9155--infallible-bardeen-164bc9.netlify.app/stable/yugabyte-platform/overview/install/ and https://deploy-preview-9155--infallible-bardeen-164bc9.netlify.app/stable/yugabyte-platform/overview/configure/

**Comment by polarweasel** [comment]
I've added an alias for the platform/overview link to install. Maybe i should make the link hit public-cloud instead, though.

**Comment by polarweasel** [comment]
(fixed both links on overview to point directly to what they should)

**Comment by ddhodge** [comment]
Similar Problem links:
Core>Explore>Fault tolerance
Core>Explore>Follower Reads
Core>Explore>Colocated Tables
Core>Explore>CDC
Core>Explore>Security
Core>Develop>Best Practices
Core>Deploy>Public Clouds>AWS
Core>Deploy>Public Clouds>GCP
Core>Deploy>Public Clouds>Azure
Core>Deploy>Kubernetes>Single>[all]
Core>Deploy>Kubernetes>Multi Zone>[all]
Core>Deploy>Kubernetes>Multo Cluster>[all]
Core>Deploy>Docker
Core>Manage>Migrate>[all]
Core>Troubleshoot>Cluster>Recover
Platform>Install>Prepare
Platform>Install>Install
Platform>Backup>Backup
Platform>Backup>Restore
Platform>Backup>Schedule
Reference>CLIs>ycqlsh

**Comment by lizayugabyte** [comment]
So, have all the "Problem links" from Dwight's list been fixed?

**Comment by ddhodge** [comment]
> So, have all the "Problem links" from Dwight's list been fixed?

Yes I checked them all

**Comment by ddhodge** [comment]
Links on https://deploy-preview-9155--infallible-bardeen-164bc9.netlify.app/stable/quick-start/build-apps/ are broke

**Review by ddhodge — APPROVED** [review]
LGTM

**Pull request merged**
