### PR TITLE
[doc] PR for To Docker docs, add info for starting yugabytedb in a single container

### PR DESCRIPTION
**Pull request by lizayugabyte**
Preview: 
https://deploy-preview-13306--infallible-bardeen-164bc9.netlify.app/preview/deploy/docker/docker-compose

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@sanketkedia Could you, please, review this doc PR ?

**Comment by sanketkedia** [comment]
I am not very familiar with yugabyted and docker. Probably @iSignal or @nmalladi can help with your PR @lizayugabyte

**Comment by iSignal** [comment]
@lizayugabyte : this command is documented at https://docs.yugabyte.com/preview/quick-start/docker/#create-a-local-cluster - do we need to also add this to the docker compose page? 

Personally, I don't think we need to reiterate this command on the docker compose page. If any change needs to be made to the docker compose page, it would be to remove it completely and encourage users to use yugabyted instead :)

@nmalladi filed https://github.com/yugabyte/yugabyte-db/issues/8606 so will let him comment on the need for a separate docs page.

**Comment by lizayugabyte** [comment]
@nmalladi Could you, please, take a look at Sanketh's comment and let me know what I should do with the ticket you created and the new doc to address it.

**Comment by lizayugabyte** [comment]
@nmalladi Could you, please, take a look at Sanketh's comment and let me know what I should do with the ticket you created and the new doc to address it.

**Comment by lizayugabyte** [comment]
@nmalladi Could you, please, take a look at Sanketh's comment and let me know what I should do with the ticket you created and the new doc to address it.

**Comment by lizayugabyte** [comment]
@nchandrappa Could you, please, take a look at Sanketh's comment and let me know what I should do with the ticket you created and the new doc to address it.

**Comment by lizayugabyte** [comment]
@iSignal @nbhatia-yb I haven't been able to receive any response from @nchandrappa via git or slack. Please let me know what I should do with this PR (it's been open for almost 2 months)

**Comment by lizayugabyte** [comment]
From Slack:

Sanketh I
Starting a discussion on https://github.com/yugabyte/yugabyte-db/pull/13306
[@Nikhil Chandrappa]: can you take a look at the comments and check if we still need the docker compose page at all? I personally don't think it is very useful now that we have a single docker cmd line for yugabyted, what do you think?

Nikhil Chandrappa
[@Sanketh I]: I totally agree with completely removing the docker compose page. Only thing I can think of is, yugabyted is not production ready they cannot use it for running production workloads. However I believe someone trying to run a prod database on standlone docker is super rare.
I think we can totally remove the documentation for docker compose.

Sanketh I
[@Nikhil Chandrappa]: We at least test yugabyted docker in github actions etc. The docker compose is completely unverified at this point, so I doubt it helps anyone using it on prod.

Nikhil Chandrappa
Yeah makes sense.

Liza Rekadze
Okay, thanks, I remove the page

**Comment by lizayugabyte** [comment]
This PR is too old, with too many merge conflicts. 
Closing it without merging. 
The request to remove the docker page is resolved via https://github.com/yugabyte/yugabyte-db/pull/13882

**Pull request closed without merging**
