### PR TITLE
[docs] PR for YugabyteDB Anywhere K8s Configuration wrong kubectl commands

### PR DESCRIPTION
**Pull request by lizayugabyte**

### CODE REVIEW

**Comment by lizayugabyte** [comment]
@xinghua0123 Could you, please, review this doc PR ?

**Review by xinghua0123 — CHANGES_REQUESTED** [review]
The `--as system:serviceaccount:<namespace>:yugabyte-platform-universe-management `
 statement shall be included for all three cases (global admin, namespace admin and namespace restricted).

**Comment by lizayugabyte** [comment]
@xinghua0123 Could you take another look, please?

**Comment by lizayugabyte** [comment]
@xinghua0123 Could you take another look, please?

**Review by xinghua0123 — COMMENTED** [review]
LGTM. Thanks!

**Pull request merged**
