### PR TITLE
 Add a doc page to show all flags for yb-master and yb-tserver releases #21664

### PR DESCRIPTION
**Pull request by sushmithamohanraj**
### Changes for issue https://github.com/yugabyte/yugabyte-db/issues/21664

Following are the changes made to show a all flags table:
1. New sub pages **All YB-Master Flags** and **All YB-TServer Flags** added under reference/configuration/yb-tserver and under reference/configuration/yb-master. Each page displays a table for All YB-TServer/YB-Master process flags.
2. Table column includes the Flag Name, Description, Tags and Default values. 
3. New pages added for all DB major versions in the `currentVersion.json file`. 

### High level implementation details: 
Most of the logic resides in [docs/layouts/shortcodes/flags/flag-table.html](https://github.com/yugabyte/yugabyte-db/compare/master...sushmithamohanraj:yugabyte-db:docs-flags-new?expand=1#diff-f0604e28ee7c1afc3ea23c711e7fdfffe58d81ead0a5c824aefdf2d162781dfa)
1. Fetch the parent folder name to know the series/version the new page resides in. example "preview", "stable", "v2.14". 
2. Retrieves the corresponding version, appVersion values in the `currentVersion.json` file that maintains the current DB major versions. Based on the version or alias from Step 1.
3. Reason to retrieve the `version, appVersion` based on the parent folder name from the `currentVersion.json` file is: When new folders are created for new versions and when the `currentVersion.json` is updated, no changes are required to the logic or the pages. The logic automatically picks up the the new folder/version name and looks for the corresponding `version, appVersion` in the updated `currentVersion.json` file. 
4. Builds a Url to remote fetch the flags XML file with *version, appVersion*. ex: https://downloads.yugabyte.com/releases/2.21.1.0/yugabyte-2.21.1.0-b271-tserver_flags.xml
5. Converts XML to Table format. 

### Testing:
`npm start` - ran docs page locally to test the changes.

### CODE REVIEW

**Comment by premkumr** [comment]
Thanks @sushmithamohanraj  for this change. Looks really good. Few suggestions

- Let's not show the all flags page in the sidebar
- Let's link to the all flags page from the current detailed flag pages.
- Let's make this a 2-column table rather than a 4-column table, or something like that. 
Screenshot 2024-08-15 at 12 11 46 PM
- Will will add filtering to the list later.

@hari90  - please throw in any suggestions.

**Comment by hari90** [comment]
I like this 2 column approach! For the filtering I also feel its not that important, since the browser search is good enouhg.

> current detailed flag pages

@premkumr where in the current page were your thinking this can go?

**Comment by ddhodge** [comment]
> Thank you @premkumr @hari90 for taking a look at the CR.
> 
> 1. Let's link to the all flags page from the current detailed flag pages.
>    
>    * Sure. Could you please point me to the location you suggest or provide me with the link/url to the page you refer to?
> 
> Will work on item **No.2** and wait on **No.1** before sending a 2nd revision.

For 1. I pushed a small change that I think is what Prem is getting at. We may want to reconsider the wording @hari90

**Comment by hari90** [comment]
@ddhodge the wordings look good to me.
Can we show this in the common flags page index? After Syntax, and before General flags maybe?

image

**Comment by ddhodge** [comment]
> @ddhodge the wordings look good to me. Can we show this in the common flags page index? After Syntax, and before General flags maybe?

@hari I pushed a change - something like that?

How is the wrapping in the Attributes column done? Is it manual breaks? Can it be a bit shorter so that fewer descriptions run off the table?

**Comment by premkumr** [comment]
@netlify /preview/reference/configuration/all-flags-yb-master

**Review by premkumr — COMMENTED** [review]
LGTM .

**Comment by hari90** [comment]
LGTM. Please fix the previous version yb-master.md and yb-tserver.md pages.

**Comment by ddhodge** [comment]
Thanks @sushmithamohanraj

**Pull request merged**
