### PR TITLE
[docs] changed query to use hash sharding on perf advisor pages

### PR DESCRIPTION
**Pull request by aishwarya24**
@netlify /preview/yugabyte-platform/alerts-monitoring/performance-advisor/

slack request : https://yugabyte.slack.com/archives/C05AA8K0SRH/p1685542322993719

### CODE REVIEW

**Review by ddhodge — APPROVED** [review]
LGTM

**Review by anmalysh-yb — APPROVED** [review]

**Review by anmalysh-yb — CHANGES_REQUESTED** [review]
Need to figure out if recommendation works for secondary indexes as well

**Review by anmalysh-yb — APPROVED** [review]
Example seems correct

**Comment by aishwarya24** [comment]
Thanks @anmalysh-yb for the confirmation .

**Pull request merged**
