### PR TITLE
Set Timeout and elapsed time in same units

### PR DESCRIPTION
**Pull request by srivignessh**
The elasped time is in micros-seconds and
timeout is in milliseconds for endpoint /rpcz

Set elasped time to milliseconds.

Possible Fix to #2801

### CODE REVIEW

**Comment by kmuthukk** [comment]
Thx for your contribution @srivignessh !

**Comment by rkarthik007** [comment]
Thanks indeed for the PR @srivignessh! I have added a few folks who can review this.

**Comment by srivignessh** [comment]
Thanks, @kmuthukk, and @rkarthik007.

**Comment by bmatican** [comment]
Thanks for picking this up @srivignessh ! I'll merge this in now.

Let me know if you'd like to pick up a different task, there's a handful of them that should be easy to get started with!

We are working on broadening this list and keeping it relevant: https://github.com/YugaByte/yugabyte-db/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22help+wanted%22+label%3A%22good+first+issue%22

In the meantime:
- if you'd like to see get some exposure to how we handle certs and security, this might be a nice follow up: https://github.com/yugabyte/yugabyte-db/issues/2877
- if you'd like to explore some more tooling work, this should be relatively easy to fix, but will require some setup to repro: https://github.com/yugabyte/yugabyte-db/issues/2797

**Comment by srivignessh** [comment]
@bmatican Sure. I will take a look at them. I will looking into #2877
Thanks for approving my changes and merging the commit.

**Pull request merged**
