### PR TITLE
yb footer css changes for alignment. 

### PR DESCRIPTION
**Pull request by krajasek**
This is only a short term fix and the long term fix is to enhance the page layout. Tested the change manually on Firefox and Chrome browsers.
temporary_fix_for_issue_39

### CODE REVIEW

**Comment by krajasek** [comment]
I originally reported this issue via #394.

**Comment by mbautin** [comment]
@krajasek: thank you for your contribution, and apologies for the delay! Before we can merge your pull request, could you please accept our Contributor License Agreement using the form at http://bit.ly/sign-yugabyte-cla?

**Comment by krajasek** [comment]
@mbautin: done.

**Comment by mbautin** [comment]
I think this issue was fixed in https://github.com/YugaByte/yugabyte-db/commit/199fcfa8288691ab0aabacb7d8f54c46ec01102c

**Pull request closed without merging**
