### PR TITLE
Add information on Start Master action

### PR DESCRIPTION
**Pull request by iSignal**

### CODE REVIEW

**Comment by iSignal** [comment]
@lizayugabyte @polarweasel : can we add this screenshot to the "start a new master" section? 
image

**Review by nbhatia-yb — APPROVED** [review]
LGTM Sanketh.

**Comment by lizayugabyte** [comment]
@iSignal Start and stop processes are described in this page: https://docs.yugabyte.com/preview/yugabyte-platform/manage-deployments/start-stop-processes/#start-a-process

**Comment by lizayugabyte** [comment]
@iSignal I'll add the image

**Pull request merged**
