### PR TITLE
[docs] Update release notes for 2.20.8.0-b53

### PR DESCRIPTION
**Pull request by sudhanshu456**
@netlify /preview/releases/ybdb-releases/v2.20/#v2.20.8.0

### CODE REVIEW

**Comment by premkumr** [comment]
Dont we want to make the changelog collapsible like https://docs.yugabyte.com/preview/releases/ybdb-releases/v2024.2/#change-log

cc: @ddhodge

**Comment by sudhanshu456** [comment]
>Dont we want to make the changelog collapsible like [docs.yugabyte.com/preview/releases/ybdb-releases/v2024.2#change-log](https://docs.yugabyte.com/preview/releases/ybdb-releases/v2024.2/#change-log)

@premkumr , I don't see we make collapsible for minor releases or when we don't have major feature releases/ highlights. Do you still want me to make it collapsible?

**Comment by ddhodge** [comment]
> Dont we want to make the changelog collapsible like https://docs.yugabyte.com/preview/releases/ybdb-releases/v2024.2/#change-log

The 2.20 RN predate that style, unless we want to update the entire page, but I think it's fine

**Review by ddhodge — APPROVED** [review]
LGTM

**Review by premkumr — APPROVED** [review]
LGTM

**Pull request merged**
