### PR TITLE
Fix syntax error of README.md in word "Snapshot".

### PR DESCRIPTION
**Pull request by Clcanny**

### CODE REVIEW

**Comment by Clcanny** [comment]
@rkarthik007 Hello, can you review this small change?

**Review by rkarthik007 — APPROVED** [review]
LGTM!

**Comment by rkarthik007** [comment]
Thanks for the fix, sorry about the delay @Clcanny!

**Comment by Clcanny** [comment]
> Thanks for the fix, sorry about the delay @Clcanny!

Thanks a lot for merging! Should I add me to CONTRIBUTORS.md? (maybe not?)

**Pull request merged**
