### PR TITLE
[Docs] [#11968] Update YSQL SELECT syntax to include explicit locking clauses

### PR DESCRIPTION
**Pull request by pkj415**
The following ebnf clause was appended to SELECT statement's syntax -
{ 'FOR' ( 'UPDATE' | 'NO KEY UPDATE' | 'SHARE' | 'KEY SHARE' ) [ 'OF' table_name { ',' table_name} ] [ 'SKIP LOCKED' ] };

Check this page for the change: 

@netlify /preview/api/ysql/the-sql-language/statements/dml_select/#grammar

### CODE REVIEW

**Comment by jasonyb** [comment]
Edit ysql_grammar.ebnf, not the generated files.  See also issue #2316.

**Comment by pkj415** [comment]
Thanks @jasonyb!! Updated the diff

**Comment by pkj415** [comment]
@polarweasel updated the description with details of the page. However, I don't see the change reflecting on the netlify link. Let me check.

**Comment by polarweasel** [comment]
@pkj415 merge master into your branch, and that'll trigger a Netlify update, not to mention probably resolve the merge conflicts due to `/latest` now being called `/preview`. (Also note how to tag the bot in the PR description — and note that it only notices when you do a new commit)

**Review by polarweasel — APPROVED** [review]
LGTM

**Pull request merged**
