### PR TITLE
[DOC-554][CLOUDGA-24513][ybm] VictoriaMetrics GA

### PR DESCRIPTION
**Pull request by ddhodge**
VictoriaMetrics GA

@netlify /preview/yugabyte-cloud/cloud-monitor/managed-integrations/

### CODE REVIEW

**Review by bansal01yash — COMMENTED** [review]
Minor nit, looks like there's some inconsistent formatting between the Prometheus and VictoriaMetric doc
image
image

**Comment by Nikunj-x28** [comment]
A small improvement , I would suggest is to add the updated images for the supported integrations page.
Screenshot 2024-11-28 at 12 26 26

**Review by Nikunj-x28 — CHANGES_REQUESTED** [review]
A small improvement I would request is to add the updated images for the supported integrations page.
Screenshot 2024-11-28 at 12 26 26

**Review by Nikunj-x28 — APPROVED** [review]

**Review by bansal01yash — APPROVED** [review]

**Comment by Nikunj-x28** [comment]
@ddhodge the feature looks good on prod please go ahead with merging the Doc changes

**Pull request merged**
