### PR TITLE
[DOC-281] [DOC-282] [2.21] K8s OSS Operator Documentation and update OS support page

### PR DESCRIPTION
**Pull request by aishwarya24**
@netlify /preview/quick-start/kubernetes/#yugabytedb-kubernetes-operator

Added slack request - https://yugabyte.slack.com/archives/CDQB8MEAU/p1710842793787099

### CODE REVIEW

**Review by amannijhawan — APPROVED** [review]
LGTM

**Comment by ddhodge** [comment]
What about https://docs.yugabyte.com/preview/deploy/kubernetes/single-zone/oss/yugabyte-operator/

**Comment by ddhodge** [comment]
The operator project is not public, I guess it will be soon?

**Review by ddhodge — APPROVED** [review]
LGTM

**Pull request merged**
